# Generated by Django 2.0.3 on 2018-03-16 04:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
            ],
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_in_year', models.CharField(choices=[('ene', 'enero'), ('feb', 'febrero'), ('mar', 'marzo'), ('abr', 'abril'), ('may', 'mayo'), ('jun', 'junio'), ('jul', 'julio'), ('ago', 'agosto'), ('set', 'setiembre'), ('oct', 'octubre'), ('nov', 'noviembre'), ('dic', 'diciembre')], default='ene', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='days',
            name='day_in_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Months'),
        ),
    ]
